{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trussium-operator.fullname" . }}-metrics
  labels:
    {{- include "trussium-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: https
      port: {{ .Values.metrics.service.port }}
      protocol: TCP
      targetPort: {{ .Values.metrics.service.port }}
  selector:
    {{- include "trussium-operator.selectorLabels" . | nindent 4 }}
{{- end }}
