apiVersion: v2
name: trussium-operator
description: Official Helm chart for deploying the Trussium Operator.
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.25.0-0"
home: https://github.com/trussiumhq/trussium-operator
sources:
  - https://github.com/trussiumhq/trussium-operator
maintainers:
  - name: Trussium Contributors
    url: https://github.com/trussiumhq
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/operator: "true"
