image:
  repository: ghcr.io/trussiumhq/trussium-operator
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
replicaCount: 1
podAnnotations: {}
podLabels: {}
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
metrics:
  service:
    enabled: true
    type: ClusterIP
    port: 8443
  serviceMonitor:
    enabled: false
    interval: 30s
    insecureSkipVerify: true
nodeSelector: {}
tolerations: []
affinity: {}
watchNamespace: ""
